Updated snakeyaml to 2.0
scijava/ui-behaviour pull request #26
Opened 2023-07-17 03:59 UTC by vishalsingh2972

Solves https://github.com/scijava/ui-behaviour/issues/25

2023-07-17 04:00 UTC, vishalsingh2972 commented
@ctrueden can you review this PR!

2023-07-18 13:00 UTC, imagejan commented on pom.xml
> +            <version>2.0</version>
@vishalsingh2972 for projects inheriting from `pom-scijava`, dependency versions should be overridden by `<property>` instead of hard-coding them.

2023-07-18 14:29 UTC, vishalsingh2972 commented on pom.xml
> +            <version>2.0</version>
@imagejan k will look into it once, thanks for the review!

2023-07-18 15:24 UTC, ctrueden requested changes
@vishalsingh2972 Thanks for getting this started!

With d65bfdbab447fdce8c4cde86efb55fdf203b9a02 I have done what @imagejan suggested and declared the snakeyaml version as a property. I also upgraded the POM parent to the latest pom-scijava.

But now the real work begins. You'll notice that the CI build failed. This is because the snakeyaml changed in a backwards-incompatible way. So you'll need to update the Java code to use the newer snakeyaml API.

To compile and test locally, you can run `mvn test` from the command line—or use an IDE like IntelliJ IDEA and File &rarr; Open... the `pom.xml` and open it as a Maven project.

2023-08-16 20:19 UTC, ctrueden commented
The snakeyaml 2.0 update was addressed independently by @skalarproduktraum in #27. So this PR is no longer needed!

2023-08-16 20:19 UTC, closed without merging